// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfj71HWfQ1AonkTlRs44_MR7AfHhJxuzA',
    appId: '1:464038000300:ios:b8488212edccfe66029109',
    messagingSenderId: '464038000300',
    projectId: 'sunrise-admin-efd10',
    storageBucket: 'sunrise-admin-efd10.firebasestorage.app',
    iosBundleId: 'com.sunrise.admin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADL4fUn0jW6MweBtoDG_NxGjVZfAxk2_c',
    appId: '1:464038000300:android:a821fd07db42a81b029109',
    messagingSenderId: '464038000300',
    projectId: 'sunrise-admin-efd10',
    storageBucket: 'sunrise-admin-efd10.firebasestorage.app',
  );

}